version: '3.8'

services:
  # NGINX Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sharpishly.conf:/etc/nginx/conf.d/default.conf
      - ./sharpishly.com/website/public:/var/www/app/sharpishly.com
      - ./dev.sharpishly.com/website/public:/var/www/app/dev.sharpishly.com
      - ./live.sharpishly.com/website/public:/var/www/app/live.sharpishly.com
      - ./python_app:/var/www/html/python_app
      - ./node_app:/var/www/html/node_app
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - php_fpm
      - python_app
      - node_app
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PHP-FPM Service
  php_fpm:
    build:
      context: ./sharpishly.com
      dockerfile: Dockerfile.php
    container_name: php_fpm
    restart: unless-stopped
    volumes:
      - ./sharpishly.com/website/public:/var/www/app/sharpishly.com
      - ./dev.sharpishly.com/website/public:/var/www/app/dev.sharpishly.com
      - ./live.sharpishly.com/website/public:/var/www/app/live.sharpishly.com
      - composer_cache:/root/.composer
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python App
  python_app:
    build:
      context: ./python_app
      dockerfile: Dockerfile
    container_name: python_app
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node App
  node_app:
    build:
      context: ./node_app
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    expose:
      - "4000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: sharpishly
      MYSQL_USER: sharpishly_user
      MYSQL_PASSWORD: sharpishly_pass
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  composer_cache:
