version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/sharpishly.conf:/etc/nginx/conf.d/default.conf
      - ./sharpishly.com/website/public:/var/www/app/sharpishly.com/website/public
      - ./dev.sharpishly.com/website/public:/var/www/app/dev.sharpishly.com/website/public
      - ./live.sharpishly.com/website/public:/var/www/app/live.sharpishly.com/website/public
    depends_on:
      - php
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm
    restart: unless-stopped
    volumes:
      - ./sharpishly.com/website:/var/www/app/sharpishly.com/website
      - ./dev.sharpishly.com/website:/var/www/app/dev.sharpishly.com/website
      - ./live.sharpishly.com/website:/var/www/app/live.sharpishly.com/website
      - ./dev.sharpishly.com/website/public/.well-known:/var/www/app/dev.sharpishly.com/website/public/.well-known
    environment:
      - DB_HOST=db
      - DB_USER=sharpishly_user
      - DB_PASSWORD=Addy@789xx$
      - DB_NAME=sharpishly_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: app-db-1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sharpishly_db
      - MYSQL_USER=sharpishly_user
      - MYSQL_PASSWORD=Addy@789xx$
      - MYSQL_ROOT_PASSWORD=Addy@789xx$
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAddy@789xx$"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      --default-authentication-plugin=mysql_native_password
      --port=3306
      --bind-address=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
